services:
  balancer:
    image: nginx:stable-alpine3.20
    ports:
      - 8080:80
    volumes:
      - ./templates:/etc/nginx/templates
  myapp-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./web/page:/app/web/page
      - ./web/static:/app/web/static
    restart: unless-stopped 
    environment:
      - TZ=Europe/Moscow

  myapp-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./web/page:/app/web/page
      - ./web/static:/app/web/static
    restart: unless-stopped 
    environment:
      - TZ=Europe/Moscow

  myapp-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - ./web/page:/app/web/page
      - ./web/static:/app/web/static
    restart: unless-stopped 
    environment:
      - TZ=Europe/Moscow

  
  
  