version: "3"

dotenv:
  - .env

tasks:
  up:
    cmd: docker build -t lendy1/k8s_project-myapp .
  
  manifestos:
    cmds:
      - kubectl apply -f ./kubernetes/deployment.yaml
      - kubectl apply -f ./kubernetes/service.yaml  
      - kubectl apply -f ./kubernetes/ingress.yaml
